# Generated by Django 5.2 on 2025-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_virtualhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualhost',
            name='disk_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='physicalhost',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='virtualhost',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
